DROP TABLE IF EXISTS library;
DROP TABLE IF EXISTS order_magazine;
DROP TABLE IF EXISTS `order`;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS magazine;

CREATE TABLE IF NOT EXISTS user
(
    ID         BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ROLE       VARCHAR(10)   NOT NULL DEFAULT 'REGULAR',
    FIRST_NAME VARCHAR(50)   NOT NULL,
    LAST_NAME  VARCHAR(50)   NOT NULL,
    EMAIL      VARCHAR(50)   NOT NULL,
    BIRTH_DATE TIMESTAMP     NOT NULL,
    CREATED    TIMESTAMP     NOT NULL,
    BALANCE    DECIMAL(8, 2) NOT NULL,
    PASS_HASH  INT           NOT NULL
);

CREATE TABLE IF NOT EXISTS `order`
(
    ID      BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT        NOT NULL,
    PRICE   DECIMAL(8, 2) NOT NULL,
    CREATED TIMESTAMP     NOT NULL,

    FOREIGN KEY (USER_ID) references user (ID)
);

CREATE TABLE IF NOT EXISTS magazine
(
    ID          BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50)   NOT NULL,
    DESCRIPTION VARCHAR(250)  NOT NULL,
    PERIOD_DAYS INT           NOT NULL,
    PRICE       DECIMAL(8, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_magazine
(
    ORDER_ID    BIGINT NOT NULL,
    MAGAZINE_ID BIGINT NOT NULL,
    AMOUNT      INT    NOT NULL,

    FOREIGN KEY (ORDER_ID) references `order` (ID),
    FOREIGN KEY (MAGAZINE_ID) references magazine (ID)
);

CREATE TABLE IF NOT EXISTS library
(
    USER_ID     BIGINT    NOT NULL,
    MAGAZINE_ID BIGINT    NOT NULL,
    EXPIRATION  TIMESTAMP NOT NULL,

    FOREIGN KEY (USER_ID) references user (ID),
    FOREIGN KEY (MAGAZINE_ID) references magazine (ID)
);